### ISSUE TITLE
[BUG] can't reach local Ollama

### ISSUE THREAD

**Issue by pnmartinez** [pnmartinez/ai-dashboard-builder#9]
## Bug Description
Networking with ollama running on the host seems to not work.

When selecting Ollama when running on typical port 11434 on the host, it is unreachable.

## Steps To Reproduce
1. Select local Ollama (which should be running on localhost:11434)
2. Provide a dataset
3. Click analyze button

## Logs

```
ai-dashboard-builder-dashboard-1  | 2024-12-14 14:04:53,167 - LLMPipeline - INFO - Sending request to Ollama API
ai-dashboard-builder-dashboard-1  | 2024-12-14 14:04:53,171 - LLMPipeline - ERROR - Error querying local model: HTTPConnectionPool(host='host.docker.internal', port=11434): Max retries exceeded with url: /api/generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0d6cc3fd00>: Failed to establish a new connection: [Errno 111] Connection refused'))
ai-dashboard-builder-dashboard-1  | Traceback (most recent call last):
ai-dashboard-builder-dashboard-1  |   File "/app/.venv/lib/python3.10/site-packages/urllib3/connection.py", line 199, in _new_conn
ai-dashboard-builder-dashboard-1  |     sock = connection.create_connection(
ai-dashboard-builder-dashboard-1  |   File "/app/.venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
ai-dashboard-builder-dashboard-1  |     raise err
ai-dashboard-builder-dashboard-1  |   File "/app/.venv/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
ai-dashboard-builder-dashboard-1  |     sock.connect(sa)
ai-dashboard-builder-dashboard-1  | ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by pnmartinez** [comment]
Closed with https://github.com/pnmartinez/ai-dashboard-builder/pull/10
